name: ci-cd
run-name: ${{ github.actor }} is testing CI/CD on github
on: [push]
jobs:
  build_a:
    name: Build a
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job will be run first."

  build_b:
    name: Build b
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job will be run first, in parallel with build_a"

  test_ab:
    name: Test a and b
    runs-on: ubuntu-latest
    needs: [build_a,build_b]
    steps:
      - run: echo "This job will run after build_a and build_b have finished"

  deploy_ab:
    name: Deploy a and b
    runs-on: ubuntu-latest
    needs: [test_ab]
    steps:
      - run: echo "This job will run after test_ab is complete"

